Refactor v3
Non-Euclidean-World/Hyper pull request #31
Opened 2023-09-05 09:16 UTC by KarolDenst

2023-09-05 09:19 UTC, KarolDenst commented on Hyper/Controllers/HudController.cs
> +﻿using Common;
Not sure if this class makes sense. We could just render hud elements in other controllers

2023-09-05 14:01 UTC, AleksyBalazinski requested changes
Added some comments. Also there are some warnings from github actions.
The most important things to consider are:
* The `Controller` classes
* Not working bounding boxes
* Projects vs dirs

2023-09-05 14:09 UTC, KarolDenst commented on ChunksTest/GlobalSetup.cs
It makes it so that we don't write logs when running tests

2023-09-08 11:19 UTC, KarolDenst commented on Hyper/Controllers/IController.cs
That would propably be a lot slower since we would have to set shader for every bot, every chunk... and now we just set them for all object of the same type

2023-09-08 11:23 UTC, KarolDenst commented on Physics/TypingUtils/Conversions.cs
I like having 2. Converter is only used in Character project and there is no reason to expose its methods outside this project but we do need to make Conversions public.

2023-09-08 11:25 UTC, KarolDenst commented on Common/UserInput/Context.cs
> +    private static readonly Lazy<Context> _instance = new(() => new Context());
The conventions is that it sould be Instance, but we already have Instance so i lift it with the _. Alternatively we could remove readonly or just use some different name

2023-09-08 11:39 UTC, KarolDenst commented on Hyper/Controllers/BotsController.cs
> +            // #if BOUNDING_BOXES
done

2023-09-08 13:04 UTC, KarolDenst commented on Hyper/Shaders/ShaderFactory.cs
> +            ("../../../../Characters/Shaders/model_shader.vert", ShaderType.VertexShader),
we could add something like modelShader class i just added. It is not used right now but could be used instead of normal constructors

2023-09-08 17:44 UTC, KarolDenst commented on Physics/Collisions/Bepu/CharacterControllers.cs
fixed it

2023-09-08 17:54 UTC, KarolDenst commented on Common/Meshes/Mesh.cs
> -    public virtual void RenderFullDescription(Shader shader, float scale, Vector3 cameraPosition)
I hate LightSource class. I think we will have to remake it later it anyways so I don't think theres a need to change it in this pr

2023-09-09 12:56 UTC, AleksyBalazinski approved these changes

2023-09-09 12:57 UTC, merged